
Resources:
  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: 
        Fn::GetAtt:
          - MySNSTopic
          - TopicArn
      Endpoint: 
        Fn::GetAtt:
          - MyEventsQueue
          - Arn
      Protocol: sqs