Resources:
  mySqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: mySqsQueuePolicy
        Statement:
        - Sid: Allow-sns-SendMessage
          Effect: Allow
          Principal: 
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource: "*"
          Condition: 
            ArnEquals:
              aws:SourceArn:
                Fn::GetAtt:
                - MySNSTopic
                - TopicArn
      Queues:
        - Ref: emailQueue
        - Ref: slackQueue