createUser:
  handler: src/users/createUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
          - MyAppDatabase
          - Arn
        - Fn::GetAtt:
          - MyEventsQueue
          - Arn
  environment:
    TABLE_NAME:
      Ref: MyAppDatabase
    QUEUE_URL:
      Ref: MyEventsQueue
  events:
    - http:
        method: post
        path: /v1/users

publisher:
  handler: src/users/createUser/publisher.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
          - MyEventsQueue
          - Arn
  environment:
    QUEUE_URL:
      Ref: MyEventsQueue
  events:
    - sqs:
          arn:
            Fn::GetAtt:
              - MyEventsQueue
              - Arn    
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures


deleteUser:
  handler: src/users/deleteUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref:  MyAppDatabase
  events:
    - http:
        method: delete
        path: /v1/users

getUser:
  handler: src/users/getUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref:  MyAppDatabase
  events:
    - http:
        method: get
        path: /v1/users

editUser:
  handler: src/users/editUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
        Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref:  MyAppDatabase
  events:
    - http:
        method: put
        path: /v1/users