createUser:
  handler: src/users/createUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref: MyAppDatabase
  events:
    - http:
        method: post
        path: /v1/users

deleteUser:
  handler: src/users/deleteUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref:  MyAppDatabase
  events:
    - http:
        method: delete
        path: /v1/users

getUser:
  handler: src/users/getUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:ConditionCheckItem
      Resource:
        Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref:  MyAppDatabase
  events:
    - http:
        method: get
        path: /v1/users

editUser:
  handler: src/users/editUser/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:UpdateItem
      Resource:
        Fn::GetAtt:
          - MyAppDatabase
          - Arn
  environment:
    TABLE_NAME:
      Ref:  MyAppDatabase
  events:
    - http:
        method: put
        path: /v1/users